let SectorsMixin = {
  getSectors() {
    let sectors = [
      { name: "Aldea la Ranchera" },
      { name: "Aldea Antenas" },
      { name: "Aldea Chocarima" },
      { name: "Aldea El Tambo" },
      { name: "Aldea El Topacio" },
      { name: "Aldea Estación Santa Ana" },
      { name: "Aldea La Blanquita" },
      { name: "Aldea La Cucuri La Cucuri" },
      { name: "Aldea La Cuttella del Palmar" },
      { name: "Aldea La Laguna" },
      { name: "Aldea La Libertad" },
      { name: "Aldea La Victoria" },
      { name: "Aldea Llano Grande" },
      { name: "Aldea Los Alpes" },
      { name: "Aldea Media Libra" },
      { name: "Aldea Pala de Chocara" },
      { name: "Aldea Puerto Rico" },
      { name: "Aldea Puerto Salón" },
      { name: "Aldea Quirimari" },
      { name: "Aldea Río Negro" },
      { name: "Aldea San Joaquín" },
      { name: "Aldea Santa Isabel" },
      { name: "Aldea Santa Rosa" },
      { name: "Aldea Vega Grande" },
      { name: "Aldea Veracruz Parte Alta" },
      { name: "Aldea Veracruz Parte Baja" },
      { name: "Barrio Andrés Eloy Blanco" },
      { name: "Barrio Aurelio Chacón" },
      { name: "Barrio Buenos Aires" },
      { name: "Barrio Casa de Tablas" },
      { name: "Barrio El Camping" },
      { name: "Barrio El Cementerio" },
      { name: "Barrio El Diamante" },
      { name: "Barrio El Hoyo" },
      { name: "Barrio El Milagro" },
      { name: "Barrio El Moral" },
      { name: "Barrio La Avenida" },
      { name: "Barrio La Cuchilla" },
      { name: "Barrio Las Golondrinas" },
      { name: "Barrio Las Mercedes" },
      { name: "Barrio Libertador" },
      { name: "Barrio Los Seibones" },
      { name: "Barrio Malacate" },
      { name: "Barrio San Juaquín" },
      { name: "Barrio Santa Marta" },
      { name: "Barrio Santa Teresa" },
      { name: "Barrio Sucre" },
      { name: "Barrio Timoteo Chacón" },
      { name: "Caserío Casa de Zing" },
      { name: "Caserío El 15 Rojo" },
      { name: "Caserío El Cerro" },
      { name: "Caserío El Palmar Rivereño" },
      { name: "Caserío Guacamaya" },
      { name: "Caserío La Cascada" },
      { name: "Caserío La Laja" },
      { name: "Caserío La Quinta" },
      { name: "Caserío La Selva" },
      { name: "Caserío Mata de Guamo" },
      { name: "Caserío Mesa del Tigre" },
      { name: "Caserío Santa Fe" },
      { name: "Caserío Tancipay" },
      { name: "Invasión 21 de Mayo" },
      { name: "Invasión Colinas de Manaure" },
      { name: "Invasión La Esmeralda" },
      { name: "Invasión Lomas del Viento" },
      { name: "Invasión Los Nazarenos" },
      { name: "Invasión Los Pomarrosos" },
      { name: "Invasión Puente de Oro" },
      { name: "Pasaje La Bomba" },
      { name: "Pasaje Las Mercedes" },
      { name: "Pasaje Naiguatá" },
      { name: "Sector Buena Vista" },
      { name: "Sector El Milagro" },
      { name: "Sector Estación Santa Ana" },
      { name: "Sector La Cachicama" },
      { name: "Sector La Carbona" },
      { name: "Sector La Mesa" },
      { name: "Sector La Pabellona" },
      { name: "Sector La Voladora" },
      { name: "Sector Monte Bello" },
      { name: "Sector Monte Rico" },
      { name: "Sector Morretón" },
      { name: "Sector Palmarito" },
      { name: "Sector Puente Salom" },
      { name: "Sector Quinimarí" },
      { name: "Sector Santa Ana del Táchira" },
      { name: "Sector Vega Grande" },
      { name: "Sector Veracruz" },
      { name: "Urbanización Centenario" },
      { name: "Urbanización Colinas de Córdova" },
      { name: "Urbanización Doña Carmen" },
      { name: "Urbanización El Cafetal I" },
      { name: "Urbanización El Cafetal II" },
      { name: "Urbanización El Cafetal III" },
      { name: "Urbanización El Carrizal" },
      { name: "Urbanización El Cementerio" },
      { name: "Urbanización El Diamante I" },
      { name: "Urbanización El Diamante II" },
      { name: "Urbanización Jorge Patiño" },
      { name: "Urbanización La Quebradita" },
      { name: "Urbanización Los Alvarados" },
      { name: "Urbanización Los Apamates" },
      { name: "Urbanización Los Próceres" },
      { name: "Urbanización San José" },
      { name: "Urbanización Teo Camargo" },
      { name: "Urbanización Venecia" },
      { name: "Urbanización Villa Nueva" }
    ];

    return sectors;
  }
};

export default SectorsMixin;